### Nominal/OHE Encoding

In [ ]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [ ]:
# create a simple dataframe
df = pd.DataFrame({
    'color': ['red', 'blue', 'green', 'green', 'red', 'blue']
})

In [ ]:
df.head()

In [ ]:
# create an instance of onehotencoder
encoder = OneHotEncoder()

In [ ]:
# perform fit and transform 
encoded = encoder.fit_transform(df[['color']]).toarray()

In [ ]:
import pandas as pd
encoder_df = pd.DataFrame(encoded, columns = encoder.get_feature_names_out())

In [ ]:
encoder_df

In [ ]:
# for new data
encoder.transform([['blue']]).toarray()

In [ ]:
pd.concat([df, encoder_df], axis = 1)

### Label Encoding

In [2]:
df.head()

   color
0    red
1   blue
2  green
3  green
4    red

In [4]:
from sklearn.preprocessing import LabelEncoder
lbl_encoder = LabelEncoder()

In [5]:
lbl_encoder.fit_transform(df[['color']])

d:\anaconda\Lib\site-packages\sklearn\preprocessing\_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

array([2, 0, 1, 1, 2, 0])

In [7]:
lbl_encoder.transform([['red']])

d:\anaconda\Lib\site-packages\sklearn\preprocessing\_label.py:132: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([2])

### Ordinal Encoding

In [8]:
from sklearn.preprocessing import OrdinalEncoder
df = pd.DataFrame({
    'size': ['small', 'medium', 'large', 'medium', 'small', 'large']
})

In [9]:
df

     size
0   small
1  medium
2   large
3  medium
4   small
5   large

In [10]:
# create an instance of ordinal encoder and then fit_transform (create ranking)
encoder = OrdinalEncoder(categories = [['small', 'medium', 'large']])

In [11]:
encoder.fit_transform(df[['size']])

array([[0.],
       [1.],
       [2.],
       [1.],
       [0.],
       [2.]])

### Target Guided Ordinal Encoding

In [12]:
import pandas as pd

# dataframe with a categorical variable and a target variable
df = pd.DataFrame({
    'city': ['New York', 'London', 'Paris', 'Tokyo', 'New York', 'Paris'],
    'price': [200, 150, 300, 250, 180, 320]
})

In [13]:
df

       city  price
0  New York    200
1    London    150
2     Paris    300
3     Tokyo    250
4  New York    180
5     Paris    320

In [15]:
mean_price = df.groupby('city')['price'].mean().to_dict()

In [16]:
mean_price

{'London': 150.0, 'New York': 190.0, 'Paris': 310.0, 'Tokyo': 250.0}

In [17]:
df['city_encoded'] = df['city'].map(mean_price)

In [20]:
df[['price', 'city_encoded']]

   price  city_encoded
0    200         190.0
1    150         150.0
2    300         310.0
3    250         250.0
4    180         190.0
5    320         310.0